name: Build React Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Clone repository 🔍
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    - name: Install dependencies and Build 📦
      run: |
        npm ci --ignore-scripts
        npm i @mbzcloud-test/test-package@latest
        npm run build --if-present
      env:
        GITHUB_PKG_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_PAT }}
    #
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     #name: build
    #     path: build
    #     retention-days: 5
    #
    # - name: Download all Artifacts
    #   uses: actions/download-artifact@v3
    #   #id: download
    #
    # - name: Echo download path
    #   run: echo ${{ steps.download.outputs.download-path }}

    - name: Deploy build to other repository
      uses: manzoorwanijk/action-deploy-to-repo@master
      with:
        src_dir: build
        target_owner: mbzcloud-test
        target_repo: test-react
        target_dir: infrastructure/web-client
        target_branch: builds
        access_token: ${{ secrets.GH_PACKAGE_PAT }}
        cleanup_command: "rm -rf infrastructure/"
